server:
  port: 8081
  error:
    include-message: always
    include-stacktrace: always

spring:
  application:
    name: product-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  # Configuration PostgreSQL (compatible DBeaver)
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update   # crée/maj le schéma au démarrage (pratique pour dev/soutenance)
    show-sql: true       # affiche les requêtes SQL en dev
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info

---
spring:
  config:
    activate:
      on-profile: prod
  # Configuration PostgreSQL en production (mêmes paramètres de démo)
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update   # peut être changé en 'validate' selon vos besoins
    show-sql: false


